# Generated by Django 5.1.3 on 2024-11-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='direccion',
            new_name='ubicacion',
        ),
        migrations.AddField(
            model_name='comuna',
            name='nombre_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.region'),
            preserve_default=False,
        ),
    ]
