# Generated by Django 5.1.3 on 2024-11-21 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_region_rename_direccion_direccion_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ultima_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
