# Generated by Django 5.1.3 on 2024-11-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0007_inmueble_propietario_alter_inmueble_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='m2_construidos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='m2_totales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.IntegerField(),
        ),
    ]
