# Generated by Django 5.1.3 on 2024-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0008_alter_caracteristicas_m2_construidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
